services:
  - type: web
    name: blinkit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd blinkitapp && gunicorn app:app
    repo: https://github.com/yourusername/blinkit-app.git # Update this with your actual repository
    branch: main
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true 